export function isBoolish(value: any, fieldName: any): boolean;
export function isCurrency(value: any): boolean;
export function isDateString(value: any, fieldName: any): boolean;
export function isEmailShaped(value: any): boolean;
export function isFloatish(value: any): boolean;
export function isNullish(value: any): boolean;
export function isNumeric(value: any, fieldName: any): boolean;
export function isObjectId(value: any, fieldName: any): boolean;
export function isTimestamp(value: any): boolean;
export function isUuid(value: any, fieldName: any): boolean;
