name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    # runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.14.1]
#         node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm ci
        npm test

  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Code Coverage
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        npm ci
        npm test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} #required
        # file: ./coverage/coverage.xml #optional
        flags: unittests #optional
        name: schema-analyzer #optional
        yml: ./codecov.yml #optional
        fail_ci_if_error: true #optional (default = false)

    env:
        CI: true
