name: Node.js CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: |
          sudo apt-get update && sudo apt-get install zopfli brotli
          npm ci
          npm test

  coverage:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Code Coverage
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.3
      - run: |
          npm ci
          npm test
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          # file: ./coverage/coverage.xml #optional
          flags: unittests #optional
          name: schema-analyzer #optional
          yml: ./codecov.yml #optional
          fail_ci_if_error: true #optional (default = false)

    env:
      CI: true
